### ISSUE TITLE
need the docker file

### ISSUE THREAD

**Issue by HuaizhengZhang** [MLSysOps/Active-Learning-as-a-Service#35]
#### Software execution information

AlaaS version:
System OS version:

#### Other information

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by huangyz0918** [comment]
closed via latest commit https://github.com/MLSysOps/Active-Learning-as-a-Service/commit/8d6cb255e669fed6a524fa253e1dec890281b765
